Decay functions and Generalized Costs
conveyal/docs pull request #5
Opened 2020-09-29 06:02 UTC by abyrd

This adds documentation for two new features slated for public release: distance decay functions and generalized cost from specialized OSM tags.

It also fixes a Google Analytics problem with non-production deployments of the docs.

This is marked draft because it needs another round of cleanup and writing.

2020-09-29 23:36 UTC, ansoncfit requested changes
These new sections look good overall. My main comment is that the generalized cost introduction refers to "turning times," so we should specify times in the discussion of the turn penalties.

2020-09-29 23:36 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +Specifically in the LADOT case, we use cost supplier plugins (LaDotBikeCostSupplier, LaDotWalkCostSupplier) which use OSM tags read by the LaDotCostTags class. That input OSM data must be processed i
```suggestion
Specifically in the LADOT case, we use cost supplier plugins (LaDotBikeCostSupplier, LaDotWalkCostSupplier) which use OSM tags read by the LaDotCostTags class. That input OSM data must be processed into ways that have no intersections except at their endpoints. All the required tags must be present on every edge. If not, the generalized cost functionality will be disabled. OSM data in this form is created by the data preparation scripts at https://github.com/RSGInc/ladot_analysis_dataprep. The Python OSM library used there naturally breaks ways into routable edges between intersections as required.
```

2020-09-29 23:36 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +Turn costs are defined in terms of meters traveled at a standardized speed of 1.3 meters per second (not affected by the walking speed in the analysis request). Traversing any intersection has a fixe
```suggestion
Turn costs are defined in terms of meters traveled at a standardized speed of 1.3 meters per second (not affected by the walking speed in the analysis request). Traversing any intersection has a fixed cost of 54 meters (41.5 seconds). Daily traffic over 10k adds a penalty of 28 meters (21.5 seconds) if there is no crosswalk at all; daily traffic over 13k adds a penalty of 73 meters (56.2 seconds) if there is no signalized crosswalk. The traffic figure used is the cross traffic when moving straight through an intersection; it is the greater of the traffic in the forward or backward directions when turning left (across traffic). 
```

2020-09-29 23:36 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +Turn costs are defined in terms of meters traveled at a standardized biking speed of 4 meters per second (not affected by the biking speed in the analysis request). All turns receive a penalty of 54
```suggestion
Turn costs are defined in terms of meters traveled at a standardized biking speed of 4 meters per second (not affected by the biking speed in the analysis request). All turns receive a penalty of 54 meters (13.5 seconds), which does not apply when going straight through an intersection. Stop signs and signals add 6 and 27 meters (1.5 and 6.8 seconds) respectively. 
```

2020-09-29 23:36 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +Right turns are penalized by 50 meters if the daily traffic of the cross road exceeds 10k. Left turns onto busy cross streets, and passing straight through intersections with busy streets are penaliz
```suggestion
Right turns are penalized by 50 meters (12.5 seconds) if the daily traffic of the cross road exceeds 10k. Left turns onto busy cross streets, and passing straight through intersections with busy streets are penalized in the same way: 424 meters (1 minute, 46 seconds) if the cross traffic exceeds 20k/day, 81 meters (20.3 seconds) if it exceeds 10k/day, and 78 meters (19.5 seconds) if it exceeds 5k/day.
```

2020-09-29 23:36 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +Left turns from busy streets are also affected by parallel traffic: 297 meters for over 20k/day, and 117 meters for over 10k/day.
```suggestion
Left turns from busy streets are also affected by parallel traffic: 297 meters (1 minute, 14 seconds) for over 20k/day, and 117 meters (29.3 seconds) for over 10k/day.
```

2020-09-30 15:03 UTC, abyrd commented
I did some more fact-checking and cleanup to match recent backend changes. This should be ready for review and potentially Kodiak automerge @ansoncfit

2020-09-30 15:32 UTC, ansoncfit approved these changes
👍

2020-09-30 15:32 UTC, merged