WIP Upgrade to Docusaurus V3
conveyal/docs pull request #87
Opened 2024-02-24 07:46 UTC by trevorgerhardt

2024-02-27 02:17 UTC, ansoncfit requested changes
Looks good overall. I wasn't sure about the change in the generalized cost section, so I updated it based on my understanding.

2024-02-27 02:17 UTC, ansoncfit commented on docs/learn-more/generalized-cost.mdx
> +- `unpaved_alley` is one of [true/; other]
```suggestion
- `unpaved_alley` is true (set to true for ways with `surface=unpaved` or `highway=alley` tags)
```

2024-02-27 13:58 UTC, trevorgerhardt commented
> Looks good overall. I wasn't sure about the change in the generalized cost section, so I updated it based on my understanding.

Thanks for the suggestion, looks like I had a typo there.

2024-02-28 20:54 UTC, ansoncfit approved these changes

2024-02-28 20:54 UTC, merged